
import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Enumeration;
import java.util.Random;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author piko
 */
public class Application extends javax.swing.JFrame {

    /**
     * Creates new form Application
     */
    private ArrayList<Color> list;
    private ButtonGroup group;
    private Random rand;
    private JButton card1, card2;
    private int matched,arraySize;
    private static final Color DEFAULT_COLOR = Color.DARK_GRAY;
    private int flag;

    public Application() {
        matched = 0;
        group = new ButtonGroup();
        rand = new Random();
        card1 = new JButton();
        card2 = new JButton();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mind Game");
        setAlwaysOnTop(true);
        setForeground(new java.awt.Color(121, 121, 121));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(350, 350));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        group.add(jButton1);
        jButton1.setEnabled(false);
        jButton1.setName("1"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameButtonClicked(evt);
            }
        });
        jPanel1.add(jButton1);

        group.add(jButton2);
        jButton2.setEnabled(false);
        jButton2.setName("2"); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameButtonClicked(evt);
            }
        });
        jPanel1.add(jButton2);

        group.add(jButton3);
        jButton3.setEnabled(false);
        jButton3.setName("3"); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameButtonClicked(evt);
            }
        });
        jPanel1.add(jButton3);

        group.add(jButton4);
        jButton4.setEnabled(false);
        jButton4.setName("4"); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameButtonClicked(evt);
            }
        });
        jPanel1.add(jButton4);

        group.add(jButton6);
        jButton6.setEnabled(false);
        jButton6.setName("5"); // NOI18N
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameButtonClicked(evt);
            }
        });
        jPanel1.add(jButton6);

        group.add(jButton7);
        jButton7.setEnabled(false);
        jButton7.setName("6"); // NOI18N
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameButtonClicked(evt);
            }
        });
        jPanel1.add(jButton7);

        group.add(jButton8);
        jButton8.setEnabled(false);
        jButton8.setName("7"); // NOI18N
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameButtonClicked(evt);
            }
        });
        jPanel1.add(jButton8);

        group.add(jButton9);
        jButton9.setEnabled(false);
        jButton9.setName("8"); // NOI18N
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameButtonClicked(evt);
            }
        });
        jPanel1.add(jButton9);

        group.add(jButton10);
        jButton10.setEnabled(false);
        jButton10.setName("9"); // NOI18N
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameButtonClicked(evt);
            }
        });
        jPanel1.add(jButton10);

        group.add(jButton11);
        jButton11.setEnabled(false);
        jButton11.setName("10"); // NOI18N
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameButtonClicked(evt);
            }
        });
        jPanel1.add(jButton11);

        group.add(jButton12);
        jButton12.setEnabled(false);
        jButton12.setName("11"); // NOI18N
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameButtonClicked(evt);
            }
        });
        jPanel1.add(jButton12);

        group.add(jButton13);
        jButton13.setEnabled(false);
        jButton13.setName("12"); // NOI18N
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameButtonClicked(evt);
            }
        });
        jPanel1.add(jButton13);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 164;
        gridBagConstraints.ipady = 230;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(68, 101, 12, 100);
        getContentPane().add(jPanel1, gridBagConstraints);

        jButton5.setText("Play");
        jButton5.setMinimumSize(new java.awt.Dimension(90, 90));
        jButton5.setPreferredSize(new java.awt.Dimension(90, 90));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked

        list = new ArrayList<Color>();
        arraySize = group.getButtonCount();
        float r, g, b;

        for (int i = 0; i < arraySize; i = i + 2) {
        //random color pair generation --- 
            r = rand.nextFloat();
            g = rand.nextFloat();
            b = rand.nextFloat();
            Color randColor = new Color(r, g, b);;
             
            list.add((Color) randColor);
            list.add((Color) randColor);
            //---
        }
        //shuffle array list
        Collections.shuffle(list);
        int k = 0;

        for (Enumeration<AbstractButton> buttons = group.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            button.setEnabled(true);
            button.setBackground(list.get(k++));
        }
        //timer starts
        new Reminder(3);


    }//GEN-LAST:event_jButton5MouseClicked

    private void gameButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameButtonClicked
        JButton jb;
        jb = (JButton) evt.getSource();
        if (jb.getBackground() == DEFAULT_COLOR) {
            switch (flag) {
                case 0://first card open
                    card1 = (JButton) evt.getSource();
                    card1.setBackground(list.get(Integer.parseInt(card1.getName()) - 1));
                    flag++;
                    break;
                case 1://second card open-> attempt to match
                    card2 = (JButton) evt.getSource();
                    card2.setBackground(list.get(Integer.parseInt(card2.getName()) - 1));
                    flag++;

                case 2://match cards
                    if (card1.getBackground() != card2.getBackground()) {
                        card1.setBackground(DEFAULT_COLOR);
                        card2.setBackground(DEFAULT_COLOR);
                    } else if (card1.getBackground() == card2.getBackground()) {
                        matched++;
                        if(matched==arraySize/2){
                                JOptionPane.showMessageDialog(null, "Congratulations , you win");
                                matched=0;
                        }
                    }
                    //null cards,close cards
                    card1 = null;
                    card2 = null;
                    flag = 0;
                    break;

                default:
                    System.out.println("What happened?");
                    break;
            }
        }

    }//GEN-LAST:event_gameButtonClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application().setVisible(true);

            }

        });
    }
//method for setting group color 
    void setGroupColor(Color color) {
        for (Enumeration<AbstractButton> buttons = group.getElements(); buttons.hasMoreElements();) {

            AbstractButton button = buttons.nextElement();        
            button.setBackground(color);
        }
    }
//class that handles timer
    public class Reminder {

        Timer timer;
        
        public Reminder(int seconds) {
            timer = new Timer();
            timer.schedule(new RemindTask(), seconds * 1000);
        }

        class RemindTask extends TimerTask {
            //run while timer is up
            public void run() {
                setGroupColor(DEFAULT_COLOR);
                timer.cancel(); //Terminate the timer thread
            }
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
